[workspace]
members = [
    "problem_solving_patterns",
    "searching",
    "sorting",
    "data_structures",
    "sample_problems"
]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html